- job_name: 'k3s/cadvisor'
  scheme: https
  scrape_interval: 15s
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics/cadvisor
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
    namespaces:
      names:
      - kube-system
  relabel_configs:
  - target_label: cluster_name
    replacement: "k3s"
    action: "replace"
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - source_labels: [__meta_kubernetes_node_address_InternalIP]
    target_label: node_ip
  - source_labels: [__meta_kubernetes_node_label_beta_kubernetes_io_instance_type]
    target_label: node_type
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
    replacement: $1
    action: drop

- job_name: 'k3s/kubelet'
  scheme: https
  scrape_interval: 15s
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
    namespaces:
      names:
      - kube-system
  relabel_configs:
  - target_label: cluster_name
    replacement: "k3s"
    action: "replace"
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - source_labels: [__meta_kubernetes_node_address_InternalIP]
    target_label: node_ip
  - source_labels: [__meta_kubernetes_node_label_beta_kubernetes_io_instance_type]
    target_label: node_type
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: ^kubelet_volume.*$
    replacement: $1
    action: keep

- job_name: 'kube-state-metrics'
  scheme: http
  scrape_interval: 15s
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics
  static_configs:
    - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
  relabel_configs:
  - target_label: cluster_name
    replacement: "k3s"
    action: "replace"
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - source_labels: [__meta_kubernetes_node_address_InternalIP]
    target_label: node_ip
  - source_labels: [__meta_kubernetes_node_label_beta_kubernetes_io_instance_type]
    target_label: node_type
